### ISSUE TITLE
ie9 issue

### ISSUE THREAD

**Issue by ruben-podadera** [AmericanCouncils/secure-ng-resource#8]
I have a project using secure resource that works fine on chrome/safari/firefox. I tried to see what it does with ie9. I get this error :

TypeError: Unable to get value of the property 'sessionDictKey': object is null or undefined

Anyone can confirm? Is support for ie 9 planned?

**Comment by DavidMikeSimon** [comment]
I'm closing this until/unless I can get some more information to reproduce it.
